### PR TITLE
Made website responsive

### PR DESCRIPTION
**Pull request by Mudit018**
Made website responsive.

Changes made by:
Priyal Saxena and me

### CODE REVIEW

**Comment by infern018** [comment]
LGTM,

Nice work guys...!!!

**Comment by Priyal-Saxena** [comment]
> LGTM,
> 
> Nice work guys...!!!

Thank you sir

**Comment by garvitchittora** [comment]
what is the use of these image files?

image

**Comment by Mudit018** [comment]
No use sir,
By mistake pushed these

**Comment by garvitchittora** [comment]
@Priyal-Saxena ^?

**Pull request merged**
