### PR TITLE
Fixed PHP header(...) function vulnerability

### PR DESCRIPTION
**Pull request by Mitul16**
> Sure, I will remove all the comments and make another PR.

That's great and try to add some description to the PR next time, helps us get insights about the changes...

### CODE REVIEW

**Comment by abhishekmsingh** [comment]
cc @garvitchittora @infern018

**Comment by garvitchittora** [comment]
@Mitul16 hey, Can you please create PR without formatters? It will be easy for us to review and also remove the comments from the file.

**Comment by Mitul16** [comment]
Sure, I will remove all the comments and make another PR.

**Comment by garvitchittora** [comment]
@Mitul16 Also state the problem and Push with only the lines that you have changed.

**Comment by Mitul16** [comment]
Sir, I have stated the issues in a separate file - vulnerabilities.log (deleted)

**Comment by Mitul16** [comment]
@garvitchittora  What do you mean by `Formatters`?

**Comment by garvitchittora** [comment]
Screenshot from 2021-04-18 20-26-00

there are many changes like this without these reviewing of code would be easy.

**Comment by Mitul16** [comment]
Alright, I will remove the redundant edits

**Pull request closed without merging**
